export enum MESSAGES {
  // -------------------- GENERAL --------------------
  ACCOUNT_BLOCKED = 'Account is blocked',
  ALL_FIELDS_REQUIRED = 'All fields are required',
  ID_REQUIRED = 'Id is required',
  ALREADY_EXISTS = 'Resource already exists',
  BAD_REQUEST = 'Bad request',
  CREATED = 'Created successfully',
  DELETED = 'Deleted successfully',
  FAILED = 'Operation failed',
  FORBIDDEN = 'Forbidden access',
  INVALID_ID = 'Invalid ID provided',
  INVALID_PROFILE_DATA = 'Invalid profile data',
  NO_DATA = 'No data available',
  NO_RESULTS_FOUND = 'No results found',
  NOT_FOUND = 'Resource not found',
  ALL_DATA_FOUND = 'All data found',
  OTP_NOT_VALID = 'OTP not valid',
  PAGE_OUT_OF_RANGE = 'Page number out of range',
  SERVER_ERROR = 'Internal server error',
  SUCCESS = 'Operation completed successfully',
  TEMP_USER_DATA_MISSING = 'Temporary user data missing',
  UNAUTHORIZED = 'Unauthorized access',
  UPDATED = 'Updated successfully',
  USER_BLOCKED = 'User is blocked',
  VERIFY_EMAIL = 'Please verify your email',
  RESET_PASSWORD_SENDED = 'Reset password sended successfully',

  // -------------------- STATUS ACTIONS --------------------
  ACTIVATED = 'Activated successfully',
  APPROVED = 'Approved successfully',
  DEACTIVATED = 'Deactivated successfully',
  DISABLED = 'Disabled successfully',
  ENABLED = 'Enabled successfully',
  REJECTED = 'Rejected successfully',
  UNVERIFIED = 'Marked as unverified',
  VERIFIED = 'Verified successfully',

  // -------------------- AUTH --------------------
  EMAIL_OTP_REQUIRED = 'Email and OTP are required',
  EMAIL_PASSWORD_REQUIRED = 'Email and password are required',
  EMAIL_PURPOSE_REQUIRED = 'Email and purpose are required',
  EMAIL_REQUIRED = 'Email is required',
  GOOGLE_AUTH_REQUIRED = 'Google authentication details are required',
  INVALID_GOOGLE_DATA = 'Invalid authentication data',
  GOOGLE_AUTH_SUCCESS = 'Google authentication successfully',
  INVALID_CREDENTIALS = 'Invalid credentials',
  LOGIN_SUCCESS = 'Login successful',
  LOGOUT_SUCCESS = 'Logout successful',
  PASSWORD_CHANGED = 'Password changed successfully',
  PASSWORD_INCORRECT = 'Incorrect password',
  PASSWORD_RESET_FAILED = 'Password reset failed',
  PASSWORD_RESET_SUCCESS = 'Password reset successful',
  REGISTER_SUCCESS = 'Registration successful',
  TOKEN_EXPIRED = 'Authentication token has expired',
  TOKEN_INVALID = 'Authentication token is invalid',
  TOKEN_MISSING = 'Authentication token is missing',

  // -------------------- OTP --------------------
  NO_OTP_FOUND = 'No OTP found',
  OTP_EXPIRED = 'OTP has expired',
  OTP_INVALID = 'Invalid OTP',
  OTP_PURPOSE_MISMATCH = 'OTP purpose mismatch',
  OTP_RESENT = 'OTP resent successfully',
  OTP_SENT = 'OTP sent successfully',
  OTP_VERIFIED = 'OTP verified successfully',
}
